name: Client tests

on: [ push, pull_request ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose build

      - name: Up containers
        run: docker-compose up -d

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Cliet npm ci
        run: npm ci
        working-directory: ./client

      - name: Cliet npm build
        run: npm build
        working-directory: ./client

      - name: Run tests
        run: npm run test
        working-directory: ./client

      - name: Stop containers
        if: always()
        run: docker-compose down